# Generated by Django 4.0.6 on 2022-09-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jm_realestate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='earning',
            field=models.IntegerField(),
        ),
    ]
