# Generated by Django 4.0.6 on 2022-10-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jm_realestate_app', '0003_storeproperty_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
